name: daily_attendance
on:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  daily_attendance:
    runs-on: ubuntu-latest
    name: start attendance

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: attendance
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      HUFE_USERNAME: ${{ secrets.HUFE_USERNAME }}
      HUFE_PASSWORD: ${{ secrets.HUFE_PASSWORD }}
      PHONE: ${{ secrets.PHONE }}